import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { Banner, BookingForm, Doctors, Services } from '../components'
import CoreValuesSection from '../components/CoreValuesSectio'
import Footer from '../components/Footer'
import LandingBanner from '../components/LandingBanner'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.home}>
        {/* <Banner /> */}
        <LandingBanner />
        <Services />
        <Doctors />
        <BookingForm />
        <CoreValuesSection />
        <Footer />
      </main>
    </>
  )
}
